import Layout from "@/components/Layout";
export const metadata = {
    title: 'Sale Report',
    description: 'Generated by create next app',
  }

 
  export default function SalereportLayout({ children }) {
    return <Layout>{children}</Layout> 
  }

  