import Layout from "@/components/Layout";
export const metadata = {
    title: 'Shipment Report',
    description: 'Generated by create next app',
  }

 
  export default function ShipmentreportLayout({ children }) {
    return <Layout>{children}</Layout> 
  }

  